name: Tianyu Lu
description: Computation Biology
meta_description: "Tianyu Lu, Computational Biology"

markdown: kramdown
highlighter: pygments
logo: true
paginate: 15
baseurl: /
domain_name: 'http://tianyu-lu.github.io'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         'Tianyu Lu'
